config/routes.rb
Rails.application.routes.draw do
  root :to => "messages#index"

  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
    before_create :send_message

  private
  def send_message
    begin
    response = RestClient::Request.new(
      :method => :post,
      :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :To => to,
                    :From => from }
    ).execute
  rescue RestClient::BadRequest => error
    message = JSON.parse(error.response)['message']
    errors.add(:base,message)
    throw(:abort)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
    @message = Message.new

  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_path, notice: 'Message was successfully created.'
      respond_to do |format|
        format.html{redirect_to messages_path}
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private

    def message_params
      params.require(:message).permit(:to, :from, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_errors.html.erb
<!DOCTYPE html>

<% if object.errors.any? %>
  <h3>Please fix these errors </h3>
  <ul>
    <% object.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<!DOCTYPE html>

<div class="text-center">
  <%= render "layouts/errors", :object => @message %>

    <%= form_for @message, remote: true do |f| %>
      <%= f.label :from %>
      <%= f.text_field :from %><br/><br/>
      <%= f.label :to %>
      <%= f.text_field :to %><br/><br/>
      <%= f.label :body %>
      <%= f.text_area :body, size: "24x6"%><br/>
      <%= f.submit "Send" %>
    <% end %>
</div>

app/views/messages/create.js.erb
$("#new_message").remove();
$("#new_link").show();

app/views/messages/index.html.erb
<!DOCTYPE html>

<h2><center>Welcome To Twilio</center></h2>

<h3><center>Use this service to send any message anywhere, for free</center></h3><br/><hr/>

<div class="row text-center">
  <%= link_to "Send sms", new_message_path, class:"btn", id:"new_link", remote: true%>
</div><hr/><br/>

<div class="row text-center container-fluid">

  <ul class="listdecorations">

  <% @messages.each do |message| %>

  <li>
    <strong>from: <%= message.from %><br/></strong><strong>to: <%= message.to %><br/></strong>
     text: <%= message.body %><hr/>
  </li>

  <% end %>

  </ul>

</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

app/views/messages/new.js.erb
$("#new_link").hide().after("<%= j render("form") %>")